<Project>

  <!-- the most recently-released version. last thing to change before performing release. -->
  <PropertyGroup>
    <Version>0.0.1</Version>
    <QtfyTargetFramework>net10.0</QtfyTargetFramework>
  </PropertyGroup>

  <!-- general properties -->
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <!-- packaging properties, if the repository becomes a suite of dlls, some or all
  of these properties need to move to the individual project files. -->
  <PropertyGroup>
    <Description>The .Net core library for the QuantifEye project.</Description>
    <!-- Avoid breaking the build if the file is missing -->
    <PackageReleaseNotes Condition="Exists('$(MSBuildThisFileDirectory)release_notes.txt')">
      $([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)release_notes.txt'))
    </PackageReleaseNotes>
    <PackageTags>arbitrary;extended;precision;arithmetic;bigrational;combinatorics;number;numerics;rational</PackageTags>
    <AssemblyTitle>Qtfy.Net</AssemblyTitle>
    <Authors>Qtfy Authers</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/QuantifEye/Qtfy.Net</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <!-- dotnet code analysis -->
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <!-- StyleCop -->
  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)stylecop.json" />
  </ItemGroup>

</Project>
